
version: '3.3'

networks:
  app:

services:

  rnode:
    image: rchain/rnode:${TAG}
    entrypoint:
      - /opt/docker/bin/rnode
    command: run -s -n --data_dir ./data --bonds-file ./bonds.txt --validator-private-key ${NODE_PRIVATE_KEY}
    volumes:
      - ./data:/rchain
    working_dir: /rchain
    networks:
      app:
        aliases:
          - ${NODE_NAME}

  notes:
    build: ./builds/notebook
    image: proof/nb:0.2
    command: jupyter notebook --no-browser --ip 0.0.0.0 --allow-root
    hostname: notebook
    environment:
      NODE_NAME: ${NODE_NAME}
    volumes:
      - ./notebooks:/app
    working_dir: /app
    networks:
      app:
    ports:
      - "8888:8888"
