
version: '3.3'

networks:
  app:

services:

  notes:
    build: ./builds/notebooker
    # image: pdonorio/rchain-notebooker:${NOTEBOOKER_VERSION}
    # command: jupyter notebook --no-browser --ip 0.0.0.0 --allow-root
    hostname: notebook
    environment:
      NODE_NAME: ${NODE_NAME}
      NOTEBOOK_PASSWORD: ${NOTEBOOK_PASSWORD}
    volumes:
      - ./notebooks:/app
      # - ../rho/voting:/opt/contracts/
    working_dir: /app
    networks:
      app:
    ports:
      - "8888:8888"

  rnode:
    image: rchain/rnode:${TAG}
    entrypoint:
      - /opt/docker/bin/rnode
    command: run --standalone --validator-private-key ${NODE_PRIVATE_KEY}
    volumes:
      - ./files:/rchain
      - ./files/bash.rc:/root/.bashrc
      # - ../rho/voting:/opt/contracts/
    working_dir: /rchain
    networks:
      app:
        aliases:
          - ${NODE_NAME}
