
version: '3.3'

networks:
  app:

services:

  notes:
    build: ./builds/notebooker
    # BUILDING AUTOMATICALLY ON DOCKER HUB
    # image: proofmedia/rchain-notebook:${NOTEBOOKER_VERSION}
    # command: jupyter notebook --no-browser --ip 0.0.0.0 --allow-root
    hostname: notebook
    environment:
      NODE_NAME: ${NODE_NAME}
      NOTEBOOK_PASSWORD: ${NOTEBOOK_PASSWORD}
    volumes:
      - ./notebooks:/app
      # - ../rho:/opt/contracts
    working_dir: /app
    networks:
      app:
    ports:
      - "8888:8888"

  rnode:
    image: rchain/rnode:${TAG}
    hostname: ${NODE_NAME}
    # working_dir: /rchain
    # entrypoint:
    #   - /opt/docker/bin/rnode
    command:
      - run
      - --standalone
      - --host
      - ${NODE_NAME}
      - --validator-private-key
      - ${NODE_PRIVATE_KEY}
      - --bonds-file
      - /rchain/bonds.txt
      # # avoiding reaching out
      # - --no-upnp
      # # silence kademlia with non standard port
      # - --kademlia-port
      # - '35678'
    volumes:
      - ./files:/rchain
      - ./files/bash.rc:/root/.bashrc
      # - ../rho:/opt/contracts
    networks:
      app:
        aliases:
          - ${NODE_NAME}
